import React, {useMemo, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Upload, BookOpen, LayoutDashboard, BarChart3, Settings, Search, ChevronLeft, ChevronRight, CheckCircle2, Clock3, FileText, PlayCircle, Menu, X, BrainCircuit, Sparkles, Lock, RotateCcw, Trophy, CircleCheck, ArrowRight, Flame, BookMarked} from 'lucide-react';
import './styles.css';

const seedLessons=[
{id:1,title:'The Learning Revolution',type:'Video',time:'8 min',text:'Learning is changing faster than ever. Explore the forces reshaping modern education and why active learning matters.',body:['Education is moving from passive consumption toward active, personalized learning. Digital tools make it possible to turn a large source into a structured path.','The goal is not to read everything at once. A good course breaks information into focused lessons, practice and feedback.']},
{id:2,title:'How We Learn',type:'Reading',time:'12 min',text:'Memory is a process of encoding, retrieval and reinforcement. Understanding this loop helps us design better study habits.',body:['Strong learning happens when we actively retrieve ideas instead of simply rereading them. Spaced practice gives the brain repeated opportunities to strengthen useful connections.','Try explaining a concept in your own words, then return later and recall it without looking at your notes.']},
{id:3,title:'Building Better Habits',type:'Reading',time:'10 min',text:'Small, repeatable systems beat heroic bursts of motivation. Learn how cues, routines and rewards can make learning sustainable.',body:['A learning habit becomes easier when the action is tiny, specific and attached to an existing routine. Reduce the friction between deciding to study and actually starting.','Use a two-minute start: open the lesson, set a short timer and begin. Momentum often follows action rather than preceding it.']},
{id:4,title:'The Science of Focus',type:'Video',time:'9 min',text:'Attention is limited. Explore practical techniques for reducing context switching and creating focused learning sessions.',body:['Context switching has a cost. Protect focused blocks by removing unnecessary notifications, choosing one task and defining what “done” means before you start.','A short focused session is often more valuable than a long distracted one.']},
{id:5,title:'Knowledge Into Practice',type:'Quiz',time:'6 min',text:'Test your understanding with a short assessment and see where you can improve.',body:['This knowledge check covers the key ideas from the course. Complete it to finish the learning path and receive your score.']}
];
const quizQuestions=[
{q:'Which approach best supports a sustainable learning habit?',opts:['A burst of motivation once a month','A small, repeatable system','Studying only before deadlines','Multitasking across several topics'],a:1},
{q:'What does active retrieval require the learner to do?',opts:['Reread the same paragraph repeatedly','Recall an idea without looking at the answer','Highlight every sentence','Avoid practice until the end'],a:1},
{q:'Why is reducing context switching useful?',opts:['It protects focused attention','It guarantees instant mastery','It removes the need for practice','It makes every lesson shorter'],a:0}
];

function App(){
 const [page,setPage]=useState('dashboard'); const [lessonId,setLessonId]=useState(3); const [mobile,setMobile]=useState(false);
 const [file,setFile]=useState(null); const [generating,setGenerating]=useState(false); const [generated,setGenerated]=useState(false); const [completed,setCompleted]=useState([1,2]); const [quizOpen,setQuizOpen]=useState(false); const [quizResult,setQuizResult]=useState(null);
 const progress=Math.round((completed.length/5)*100); const current=seedLessons.find(l=>l.id===lessonId)||seedLessons[0];
 const go=(p)=>{setPage(p);setMobile(false)};
 const openLesson=(id)=>{setLessonId(id);go('course')};
 const completeLesson=()=>{if(!completed.includes(current.id)) setCompleted([...completed,current.id]); if(current.id<5) setLessonId(current.id+1)};
 return <div className="app">
  <Sidebar page={page} go={go} mobile={mobile} close={()=>setMobile(false)}/>
  <main className="main"><Header onMenu={()=>setMobile(true)} page={page}/>
   {page==='dashboard'&&<Dashboard file={file} setFile={setFile} generating={generating} setGenerating={setGenerating} generated={generated} setGenerated={setGenerated} go={go}/>} 
   {page==='course'&&<Course current={current} completed={completed} progress={progress} openLesson={openLesson} completeLesson={completeLesson} setQuizOpen={setQuizOpen} quizResult={quizResult}/>} 
   {page==='progress'&&<Progress progress={progress} completed={completed} go={go}/>} 
  </main>
  {quizOpen&&<QuizModal close={()=>setQuizOpen(false)} onResult={(r)=>{setQuizResult(r);setQuizOpen(false);if(!completed.includes(5))setCompleted([...completed,5])}}/>}
 </div>
}
function Sidebar({page,go,mobile,close}){return <aside className={'sidebar '+(mobile?'open':'')}><div className="brand"><span className="brand-icon"><Sparkles size={18}/></span><span>LearnFlow</span></div><button className="mobile-close" onClick={close}><X/></button><nav><Nav icon={<LayoutDashboard/>} label="Dashboard" active={page==='dashboard'} onClick={()=>go('dashboard')}/><Nav icon={<BookOpen/>} label="My Course" active={page==='course'} onClick={()=>go('course')}/><Nav icon={<BarChart3/>} label="Progress" active={page==='progress'} onClick={()=>go('progress')}/></nav><div className="side-bottom"><div className="side-tip"><BrainCircuit size={20}/><div><b>Keep learning</b><small>Consistency beats intensity.</small></div></div><Nav icon={<Settings/>} label="Settings"/></div></aside>}
function Nav({icon,label,active,onClick}){return <button className={'nav '+(active?'active':'')} onClick={onClick}>{icon}<span>{label}</span></button>}
function Header({onMenu,page}){return <header><button className="hamb" onClick={onMenu}><Menu/></button><div className="crumb"><span>LearnFlow</span><b>/</b>{page==='dashboard'?'Dashboard':page==='progress'?'Progress':'My Course'}</div><div className="header-right"><div className="search"><Search size={17}/><input placeholder="Search courses"/></div><div className="avatar">VS</div></div></header>}
function Dashboard({file,setFile,generating,setGenerating,generated,setGenerated,go}){
 const input=useRef(); const [drag,setDrag]=useState(false);
 const select=(f)=>{if(!f)return; if(!['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/msword','text/plain'].includes(f.type)&&!f.name.match(/\.(pdf|docx?|txt)$/i)){alert('Please select a PDF, DOCX, DOC or TXT file.');return} setFile(f);setGenerated(false)};
 const generate=()=>{if(!file)return;setGenerating(true);setTimeout(()=>{setGenerating(false);setGenerated(true)},1500)};
 return <div className="content dashboard"><div className="page-intro"><div><div className="eyebrow">AI LEARNING WORKSPACE</div><h1>Turn any book into a course.</h1><p>Upload a long-form document and transform it into lessons, practice and measurable progress.</p></div><button className="primary" onClick={()=>input.current?.click()}><Upload size={17}/> Upload document</button></div>
 <input ref={input} type="file" hidden accept=".pdf,.doc,.docx,.txt" onChange={e=>select(e.target.files?.[0])}/>
 <div className={'upload-zone '+(drag?'drag':'')} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);select(e.dataTransfer.files?.[0])}} onClick={()=>!file&&input.current?.click()}>
  {!file?<><div className="upload-icon"><Upload size={28}/></div><h2>Drop your document here</h2><p>or click to browse from your computer</p><span className="file-types"><FileText size={14}/> PDF, DOCX, DOC or TXT · up to 50 MB</span></>:<><div className="file-selected"><FileText size={30}/></div><h2>{file.name}</h2><p>{(file.size/1024/1024).toFixed(2)} MB · Ready to generate</p>{!generated&&<button className="primary generate" disabled={generating} onClick={e=>{e.stopPropagation();generate()}}><Sparkles size={17}/>{generating?'Generating course…':'Generate course'}</button>}{generated&&<div className="success"><CircleCheck size={17}/> Course generated · 5 lessons created</div>}<button className="text-button" onClick={e=>{e.stopPropagation();input.current?.click()}}>Choose a different file</button></>}
 </div>
 <div className="stats"><Stat icon={<BookMarked/>} label="Courses created" value="4"/><Stat icon={<Clock3/>} label="Learning hours" value="12.6"/><Stat icon={<Flame/>} label="Current streak" value="7 days"/></div>
 <section className="continue"><div className="section-head"><div><div className="eyebrow">CONTINUE LEARNING</div><h2>The Learning Revolution</h2></div><button className="link-button" onClick={()=>go('course')}>Open course <ArrowRight size={16}/></button></div><div className="course-mini" onClick={()=>go('course')}><div className="cover"><BookOpen/></div><div className="mini-main"><b>Learning: A Journey</b><span>Lesson 3 of 5 · Building Better Habits</span><div className="progress-line"><i style={{width:'60%'}}/></div></div><strong>60%</strong></div></section>
 </div>}
function Stat({icon,label,value}){return <div className="stat"><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></div>}
function Course({current,completed,progress,openLesson,completeLesson,setQuizOpen,quizResult}){return <div className="content course-page"><section className="course-hero"><div><span className="pill"><Sparkles size={13}/> AI-GENERATED COURSE</span><h1>The Learning Revolution</h1><p>Turn <b>Learning: A Journey</b> into a guided learning experience with lessons and practice.</p><div className="course-progress"><div className="progress-line"><i style={{width:progress+'%'}}/></div><b>{progress}%</b><span>complete</span></div></div><div className="book-cover"><BookOpen size={40}/><small>LEARNING:<br/>A JOURNEY</small></div></section>
 <div className="course-grid"><aside className="lesson-list"><div className="list-head"><b>Course content</b><span>5 lessons</span></div>{seedLessons.map(l=>{const done=completed.includes(l.id);return <button key={l.id} className={'lesson '+(current.id===l.id?'selected':'')} onClick={()=>openLesson(l.id)}><span className={'lesson-number '+(done?'done':'')}>{done?<CheckCircle2 size={18}/>:l.id}</span><span className="lesson-copy"><b>{l.title}</b><small>{l.type} · {l.time}</small></span>{l.id===5&&quizResult&&<Trophy size={16}/>}</button>})}</aside>
 <article className="lesson-view"><div className="lesson-meta"><span>LESSON {String(current.id).padStart(2,'0')}</span><span><Clock3 size={15}/> {current.time}</span></div><h2>{current.title}</h2><p className="lead">{current.text}</p>{current.type==='Video'?<div className="media-card"><div className="play-circle"><PlayCircle size={46}/></div><b>Lesson video</b><span>Tap play to explore this lesson</span></div>:<div className="reading"><h3>Key ideas</h3>{current.body.map((p,i)=><p key={i}>{p}</p>)}</div>}{current.id===3&&<div className="ai-insight"><Sparkles size={20}/><div><b>AI study insight</b><p>Try the “2-minute start”: commit to only two minutes. Starting reduces friction and makes the next step easier.</p></div></div>}{current.id===5&&quizResult&&<div className="result-banner"><Trophy size={22}/><div><b>Quiz completed: {quizResult.score}/{quizResult.total}</b><span>Great work — your course progress has been updated.</span></div></div>}
 <div className="lesson-footer"><button className="secondary" disabled={current.id===1} onClick={()=>openLesson(current.id-1)}><ChevronLeft size={17}/> Previous</button>{current.id===5?<button className="primary" onClick={()=>setQuizOpen(true)}>{quizResult?'Retake quiz':'Take quiz'} <ArrowRight size={17}/></button>:<button className="primary" onClick={completeLesson}>{completed.includes(current.id)?'Completed':'Mark complete'} <CheckCircle2 size={17}/></button>}</div></article></div></div>}
function Progress({progress,completed,go}){return <div className="content progress-page"><div className="eyebrow">YOUR LEARNING</div><h1>Progress overview</h1><p className="subtitle">Track your course completion and keep your momentum going.</p><div className="progress-panel"><div className="progress-top"><div><span>Overall course completion</span><strong>{progress}%</strong></div><Trophy size={30}/></div><div className="progress-line big"><i style={{width:progress+'%'}}/></div><div className="progress-meta"><span>{completed.length} of 5 lessons completed</span><span>7 day streak</span></div></div><div className="stats"><Stat icon={<CheckCircle2/>} label="Lessons completed" value={`${completed.length} / 5`}/><Stat icon={<Clock3/>} label="Study time" value="12.6h"/><Stat icon={<Flame/>} label="Current streak" value="7 days"/></div><div className="lesson-progress"><h2>Lesson progress</h2>{seedLessons.map(l=><button key={l.id} onClick={()=>go('course')}><span className={'check '+(completed.includes(l.id)?'done':'')}>{completed.includes(l.id)&&<CheckCircle2 size={16}/>}</span><span><b>{l.title}</b><small>{completed.includes(l.id)?'Completed':'Not completed'} · {l.time}</small></span><span className="status">{completed.includes(l.id)?'Done':'Start'}</span></button>)}</div></div>}
function QuizModal({close,onResult}){const [idx,setIdx]=useState(0),[answers,setAnswers]=useState([]),[selected,setSelected]=useState(null);const q=quizQuestions[idx];const submit=()=>{const next=[...answers,selected];if(idx<quizQuestions.length-1){setAnswers(next);setIdx(idx+1);setSelected(null)}else{const score=next.reduce((n,a,i)=>n+(a===quizQuestions[i].a?1:0),0);onResult({score,total:quizQuestions.length})}};return <div className="modal-back"><div className="quiz-modal"><button className="modal-x" onClick={close}><X/></button><div className="quiz-top"><span className="quiz-icon"><BrainCircuit/></span><div><span className="eyebrow">KNOWLEDGE CHECK</span><b>Question {idx+1} of {quizQuestions.length}</b></div></div><div className="quiz-progress"><i style={{width:((idx+1)/quizQuestions.length)*100+'%'}}/></div><h2>{q.q}</h2><p className="hint">Hint: Identify what the question asks and compare each option against its stated conditions.</p><div className="answers">{q.opts.map((o,i)=><button key={o} className={'answer '+(selected===i?'picked':'')} onClick={()=>setSelected(i)}><span>{String.fromCharCode(65+i)}</span>{o}</button>)}</div><button className="primary full" disabled={selected===null} onClick={submit}>{idx===quizQuestions.length-1?'Submit quiz':'Next question'} <ArrowRight size={17}/></button></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
